// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var comp = ReasonReact.reducerComponent("Routes");

function make(children) {
  return /* record */[
          /* debugName */comp[/* debugName */0],
          /* reactClassInternal */comp[/* reactClassInternal */1],
          /* handedOffState */comp[/* handedOffState */2],
          /* willReceiveProps */comp[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var routeWatcherId = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      return Curry._1(self[/* send */3], /* UpdateUrl */[url]);
                    }));
              return Curry._1(self[/* onUnmount */4], (function () {
                            return ReasonReact.Router[/* unwatchUrl */2](routeWatcherId);
                          }));
            }),
          /* didUpdate */comp[/* didUpdate */5],
          /* willUnmount */comp[/* willUnmount */6],
          /* willUpdate */comp[/* willUpdate */7],
          /* shouldUpdate */comp[/* shouldUpdate */8],
          /* render */(function (self) {
              return Curry._1(children, self[/* state */1][/* url */0]);
            }),
          /* initialState */(function () {
              return /* record */[/* url */ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0)];
            }),
          /* retainedProps */comp[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* url */action[0]]]);
            }),
          /* jsElementWrapped */comp[/* jsElementWrapped */13]
        ];
}

export {
  comp ,
  make ,
  
}
/* comp Not a pure module */
