// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Link$PwaReason from "./Router/Link.bs.js";
import * as Error$PwaReason from "./Error.bs.js";
import * as Utils$PwaReason from "./utils.bs.js";
import * as Routes$PwaReason from "./Router/Routes.bs.js";
import * as Dashboard$PwaReason from "./Dashboard.bs.js";

var myLinks = /* :: */[
  /* tuple */[
    "/",
    "Home"
  ],
  /* :: */[
    /* tuple */[
      "/error",
      "Error"
    ],
    /* [] */0
  ]
];

var component = ReasonReact.statelessComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "app"
                        }, React.createElement("h1", undefined, Utils$PwaReason.renderString("My App")), React.createElement("p", undefined, Utils$PwaReason.renderString("Hell World")), React.createElement("nav", undefined, React.createElement("ul", undefined, Utils$PwaReason.renderListJSX((function (param) {
                                        var path = param[0];
                                        return React.createElement("li", {
                                                    key: path
                                                  }, ReasonReact.element(undefined, undefined, Link$PwaReason.make(path, /* array */[Utils$PwaReason.renderString(param[1])])));
                                      }), myLinks))), React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Routes$PwaReason.make((function (url) {
                                        var match = url[/* path */0];
                                        if (match) {
                                          return ReasonReact.element(undefined, undefined, Error$PwaReason.make(/* array */[]));
                                        } else {
                                          return ReasonReact.element(undefined, undefined, Dashboard$PwaReason.make(/* array */[]));
                                        }
                                      })))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  myLinks ,
  component ,
  make ,
  
}
/* component Not a pure module */
