// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var comp = ReasonReact.statelessComponent("Dashboard");

function make() {
  return /* record */[
          /* debugName */comp[/* debugName */0],
          /* reactClassInternal */comp[/* reactClassInternal */1],
          /* handedOffState */comp[/* handedOffState */2],
          /* willReceiveProps */comp[/* willReceiveProps */3],
          /* didMount */comp[/* didMount */4],
          /* didUpdate */comp[/* didUpdate */5],
          /* willUnmount */comp[/* willUnmount */6],
          /* willUpdate */comp[/* willUpdate */7],
          /* shouldUpdate */comp[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("span", undefined, "Dashboard");
            }),
          /* initialState */comp[/* initialState */10],
          /* retainedProps */comp[/* retainedProps */11],
          /* reducer */comp[/* reducer */12],
          /* jsElementWrapped */comp[/* jsElementWrapped */13]
        ];
}

export {
  comp ,
  make ,
  
}
/* comp Not a pure module */
