// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function renderString(prim) {
  return prim;
}

function renderArray(prim) {
  return prim;
}

var renderList = $$Array.of_list;

function renderListJSX(renderMethod, listItems) {
  return $$Array.of_list(List.map(renderMethod, listItems));
}

var pushRoute = ReasonReact.Router[/* push */0];

var watchUrl = ReasonReact.Router[/* watchUrl */1];

var unwatchUrl = ReasonReact.Router[/* unwatchUrl */2];

var getInitialRoute = ReasonReact.Router[/* dangerouslyGetInitialUrl */3];

export {
  renderString ,
  renderArray ,
  renderList ,
  renderListJSX ,
  pushRoute ,
  watchUrl ,
  unwatchUrl ,
  getInitialRoute ,
  
}
/* ReasonReact Not a pure module */
